version: '3.7'

services:
  billing-worker-service:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: billing-worker-service
    ports:
      - '${PORT}:3002'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
  

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
